### ISSUE TITLE
MacOS 10.10 / make install failed: Validation failed

### ISSUE THREAD

**Issue by aneitzel** [bgamari/gnuradio-multimode#1]
Hello, 

i used latest GNUradio with HackRF and RTL-SDR under MacOS 10.10 and it working fine. Osmocom_fft and other GNUstuff is running.  Then i try to install gnuradio-multimode.
I clone the git to my homeDir and got following error after type make install. Any Idea whats wong?
## thanks, André

Mac OS; Clang version 6.1.0 (clang-602.0.53); Boost_105800; UHD_003.008.004-MacPorts-Release

Validation failed:

Block - sc_list_len - Variable(variable):
    Param - Value(value):
        Value "len(sc_list)" cannot be evaluated:
        name 'sc_list' is not defined

Block - variable_static_text_1 - WX GUI Static Text(variable_static_text):
    Param - Default Value(value):
        Value "cur_freq" cannot be evaluated:
        name 'cur_freq' is not defined

Block - sc_list_str - WX GUI Text Box(variable_text_box):
    Param - Default Value(value):
        Value "flist" cannot be evaluated:
        name 'flist' is not defined

Block - samp_rate - Variable(variable):
    Param - Value(value):
        Value "int(mh.get_good_rate(devinfo,srate))" cannot be evaluated:
        name 'mh' is not defined

Block - variable_static_text_0_0 - WX GUI Static Text(variable_static_text):
    Param - Default Value(value):
        Value "samp_rate" cannot be evaluated:
        name 'samp_rate' is not defined

Block - mode - WX GUI Chooser(variable_chooser):
    Check "$value in $choices" did not evaluate.

Block - mode - WX GUI Chooser(variable_chooser):
    Check "not $labels or len($labels) == len($choices)" did not evaluate.

Block - mode - WX GUI Chooser(variable_chooser):
    Param - Choices(choices):
        Value "mh.get_modes_values()" cannot be evaluated:
        name 'mh' is not defined

Block - mode - WX GUI Chooser(variable_chooser):
    Param - Labels(labels):
        Value "mh.get_modes_names()" cannot be evaluated:
        name 'mh' is not defined

Block - sc_list - Variable(variable):
    Param - Value(value):
        Value "eval("["+sc_list_str+"]")" cannot be evaluated:
        name 'sc_list_str' is not defined

Block - import_0_0_0 - Import(import):
    Param - Import(import):
        Import "import multimode_helper as mh" failed.

Block - probe_mult - Variable(variable):
    Param - Value(value):
        Value "1.0/math.sqrt(mh.get_mode_deviation(mode,bw))*250.0" cannot be evaluated:
        name 'mh' is not defined

Block - blocks_multiply_const_vxx_0 - Multiply Const(blocks_multiply_const_vxx):
    Check "len($const) == $vlen" did not evaluate.

Block - blocks_multiply_const_vxx_0 - Multiply Const(blocks_multiply_const_vxx):
    Param - Constant(const):
        Value "1.0 if mh.get_mode_type(mode) == "FM" else 0.0" cannot be evaluated:
        name 'mh' is not defined

Block - blocks_multiply_const_vxx_2 - Multiply Const(blocks_multiply_const_vxx):
    Check "len($const) == $vlen" did not evaluate.

Block - blocks_multiply_const_vxx_2 - Multiply Const(blocks_multiply_const_vxx):
    Param - Constant(const):
        Value "0.55 if mh.get_mode_type(mode) == "AM" else 0.0" cannot be evaluated:
        name 'mh' is not defined

Block - blocks_multiply_const_vxx_1 - Multiply Const(blocks_multiply_const_vxx):
    Check "len($const) == $vlen" did not evaluate.

Block - blocks_multiply_const_vxx_1 - Multiply Const(blocks_multiply_const_vxx):
    Param - Constant(const):
        Value "0.85 if mh.get_mode_type(mode) == "SSB" else 0.0" cannot be evaluated:
        name 'mh' is not defined

Block - k - Variable(variable):
    Param - Value(value):
        Value "wbfm/(2_math.pi_mh.get_mode_deviation(mode,bw))" cannot be evaluated:
        name 'mh' is not defined

Block - gr_fft_filter_xxx_2 - FFT Filter(fft_filter_xxx):
    Param - Taps(taps):
        Value "main_taps" cannot be evaluated:
        name 'main_taps' is not defined

Block - main_taps - Variable(variable):
    Param - Value(value):
        Value "firdes.low_pass(1.0,wbfm,mh.get_mode_deviation(mode,bw)*1.05,mh.get_mode_deviation(mode,bw)/2.0,firdes.WIN_HAMMING,6.76)" cannot be evaluated:
        name 'mh' is not defined

Block - analog_quadrature_demod_cf_0 - Quadrature Demod(analog_quadrature_demod_cf):
    Param - Gain(gain):
        Value "k" cannot be evaluated:
        name 'k' is not defined

Block - cur_freq - Variable(variable):
    Param - Value(value):
        Value "mh.scan_freq_out(sc_ena,sc_low,sc_high,freq,ifreq,scan_power+1.0e-14,thresh,sc_incr,scan_rate,sc_listm,sc_list)" cannot be evaluated:
        name 'mh' is not defined

Block - wxgui_waterfallsink2_0 - WX GUI Waterfall Sink(wxgui_waterfallsink2):
    Param - Sample Rate(samp_rate):
        Value "samp_rate/zoom" cannot be evaluated:
        name 'samp_rate' is not defined

Block - wxgui_waterfallsink2_0 - WX GUI Waterfall Sink(wxgui_waterfallsink2):
    Param - Baseband Freq(baseband_freq):
        Value "mh.get_last_returned(freq_update)" cannot be evaluated:
        name 'mh' is not defined

Block - wxgui_fftsink2_0 - WX GUI FFT Sink(wxgui_fftsink2):
    Param - Sample Rate(samp_rate):
        Value "samp_rate/zoom" cannot be evaluated:
        name 'samp_rate' is not defined

Block - wxgui_fftsink2_0 - WX GUI FFT Sink(wxgui_fftsink2):
    Param - Baseband Freq(baseband_freq):
        Value "mh.get_last_returned(freq_update)" cannot be evaluated:
        name 'mh' is not defined

Block - digifn - Variable(variable):
    Param - Value(value):
        Value ""/dev/null" if mh.get_mode_type(mode) != "DIG" else dfifo" cannot be evaluated:
        name 'mh' is not defined

Block - gr_multiply_const_vxx_0 - Multiply Const(blocks_multiply_const_vxx):
    Check "len($const) == $vlen" did not evaluate.

Block - gr_multiply_const_vxx_0 - Multiply Const(blocks_multiply_const_vxx):
    Param - Constant(const):
        Value "complex(probe_mult)" cannot be evaluated:
        name 'probe_mult' is not defined

Block - zoom_taps - Variable(variable):
    Param - Value(value):
        Value "firdes.low_pass(1.0,samp_rate,zoomed_lp,zoomed_lp/3,firdes.WIN_HAMMING,6.76)" cannot be evaluated:
        name 'samp_rate' is not defined

Block - zoomed_lp - Variable(variable):
    Param - Value(value):
        Value "(samp_rate/2.1)/zoom" cannot be evaluated:
        name 'samp_rate' is not defined

Block - gr_fft_filter_xxx_0 - FFT Filter(fft_filter_xxx):
    Param - Decimation(decim):
        Value "int(samp_rate/wbfm)" cannot be evaluated:
        name 'samp_rate' is not defined

Block - gr_fft_filter_xxx_0 - FFT Filter(fft_filter_xxx):
    Param - Taps(taps):
        Value "firdes.low_pass(1.0,samp_rate,98.5e3,66e3,firdes.WIN_HAMMING,6.76)" cannot be evaluated:
        name 'samp_rate' is not defined

Block - gr_fft_filter_xxx_3 - FFT Filter(fft_filter_xxx):
    Param - Taps(taps):
        Value "zoom_taps" cannot be evaluated:
        name 'zoom_taps' is not defined

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Sample Rate (sps)(sample_rate):
        Value "samp_rate" cannot be evaluated:
        name 'samp_rate' is not defined

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Ch0: Frequency (Hz)(freq0):
        Value "cur_freq+(upc_offset+float(upc))+fine+xfine" cannot be evaluated:
        name 'cur_freq' is not defined

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Ch0: Gain Mode(gain_mode0):
        Expression "0" is invalid for type bool.

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Ch1: Gain Mode(gain_mode1):
        Expression "0" is invalid for type bool.

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Ch2: Gain Mode(gain_mode2):
        Expression "0" is invalid for type bool.

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Ch3: Gain Mode(gain_mode3):
        Expression "0" is invalid for type bool.

Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
    Param - Ch4: Gain Mode(gain_mode4):
        Expression "0" is invalid for type bool.
Error during file compilation.
make: **\* [multimode.py] Error 1
mac:gnuradio-multimode Andre$

**Comment by bgamari** [comment]
Unfortunately my laptop died tonight; it may be a few days until I have a chance to look at this. Ping me in a week if you don't hear back.

**Comment by aneitzel** [comment]
Hi, im figured something out. Blockmessages are gone after delete and readd OSMOCOM Source into the Flowgraph. Anyway i got an error during execute the flowgraph in GNUcompanion:

Error:
Traceback (most recent call last):
  File "/Users/alpha/gnuradio-multimode/multimode.py", line 1089, in <module>
    tb = multimode(freq=options.freq, ppm=options.ppm, vol=options.vol, ftune=options.ftune, xftune=options.xftune, srate=options.srate, upclo=options.upclo, devinfo=options.devinfo, agc=options.agc, arate=options.arate, upce=options.upce, mthresh=options.mthresh, flist=options.flist, mbw=options.mbw, deemph=options.deemph, dmode=options.dmode, dfifo=options.dfifo, aout=options.aout, ahw=options.ahw)
  File "/Users/alpha/gnuradio-multimode/multimode.py", line 515, in **init**
    self.audio_sink_1 = audio.sink(int(arate), ahw, True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gnuradio/audio/audio_swig.py", line 221, in make
    return _audio_swig.sink_make(_args, *_kwargs)
RuntimeError: audio_osx_sink::setup

I can execute the flowgraph after disable the AUDIO-SINK (but without audio). I found a similar post regarding this issue on: http://www.rtl-sdr.com/forum/viewtopic.php?f=7&t=239 
I use latest GNUradio 3.7.7.1

regards André

**Comment by RobertJHarris** [comment]
I would appreciate any available information on this. I installed gnuradio on OSX 10.10 a couple of days ago, and tried just now to get gnuradio-multimode run. I get exactly the same errors as in the OP. 

Running gnuradio 3.7.8. Is multimode working for others now on 3.7.x?

**Comment by aneitzel** [comment]
Hi Robert, 

you tried to delete the Audio SINK in your GRC flowgraph? After doing that, the GUI fire up, but with audio output. So the problem seems to be related to audio output or variables.

**Comment by RobertJHarris** [comment]
Hi,

I deleted the audio sink as well as fixed a python path problem I had (gnuradio-companion redefines PYTHONPATH for me, so that was part of it, I think).  Those two things fixed most of the issues, but I still get:

Error 0:
Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
  Param - Ch1: Gain Mode(gain_mode1):
    Expression "0" is invalid for type bool.

Error 1:
Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
  Param - Ch2: Gain Mode(gain_mode2):
    Expression "0" is invalid for type bool.

Error 2:
Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
  Param - Ch3: Gain Mode(gain_mode3):
    Expression "0" is invalid for type bool.

Error 3:
Block - osmosdr_source_0 - osmocom Source(osmosdr_source):
  Param - Ch4: Gain Mode(gain_mode4):
    Expression "0" is invalid for type bool. 

and I don't seem to be able to get rid of it. I'll try poking around some more.

**Comment by maxwyb** [comment]
Same issue here on Ubuntu 14.04 LTS. I have GNURadio 3.7 built and installed, and the newest version of rtl-sdr "git-cloned" from its official repository. The core components of rtl-sdr work correctly with my rtl2832 USB dongle, such as listening to FM radios.
